import type { Metadata } from "next";
import { Sniglet } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";

// ✅ Import the font
const sniglet = Sniglet({
  subsets: ["latin"],
  weight: ["400", "800"], // you can customize weights
  display: "swap",
});

// ✅ Metadata
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// ✅ Layout
export default function AppLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* Apply font globally */}
      <body
        className={`${sniglet.className} antialiased text-foreground`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
