import type { Metadata } from "next";
import { Poppins, Sniglet } from "next/font/google";
import "./globals.css";

// ✅ Import the font
const exo2 = Sniglet({
  subsets: ["latin"],
  weight: ["400", "800"], // you can customize weights
  display: "swap",
});

// ✅ Metadata
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// ✅ Layout
export default function AppLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* Apply font globally */}
      <body className={`${exo2.className} antialiased bg-background text-foreground`}>
        {children}
      </body>
    </html>
  );
}
